development:
  adapter: postgresql
  database: bikeability_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bikeability_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bikeability_production
  pool: 5
  timeout: 5000
